[package]
name = "untitled1"
version = "0.1.0"
authors = ["lasthope"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.0"